const { Schema, model, Types } = require('mongoose');

const CanvasNodeSchema = new Schema(
  {
    itemId: { type: Types.ObjectId, ref: 'Item', required: true },
    x: { type: Number, default: 0 },
    y: { type: Number, default: 0 },
    z: { type: Number, default: 0 },
  },
  { _id: false }
);

const OutfitSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true, default: '' },
    itemIds: [{ type: Types.ObjectId, ref: 'Item' }],
    occasion: {
      type: String,
      enum: ['Casual', 'Work', 'Party', 'Formal', 'Sports', ''],
      default: '',
    },
    season: {
      type: String,
      enum: ['Summer', 'Winter', 'Spring', 'Fall', 'All Season', ''],
      default: '',
    },
    coverImage: { type: String, default: '' },
    canvas: {
      nodes: { type: [CanvasNodeSchema], default: [] },
    },

    // ── AI fields ──────────────────────────────────────────────────────────
    aiGenerated: { type: Boolean, default: false },
    // 0–100 compatibility score calculated by outfitGenerator service
    styleScore: { type: Number, min: 0, max: 100 },
    // Type of color harmony detected
    colorHarmony: {
      type: String,
      enum: ['complementary', 'analogous', 'triadic', 'monochromatic', 'neutral', 'mixed', ''],
      default: '',
    },
    // Natural language description generated by LLM
    aiDescription: { type: String, default: '' },
  },
  { timestamps: true }
);

OutfitSchema.index({ occasion: 1 });
OutfitSchema.index({ season: 1 });
OutfitSchema.index({ aiGenerated: 1 });
OutfitSchema.index(
  { name: 'text', description: 'text', aiDescription: 'text' },
  { name: 'outfit_text_search' }
);

module.exports = model('Outfit', OutfitSchema);
